version: '3.9'
name: energy-sector

services:
  mssql-db:
    image: mcr.microsoft.com/mssql/server
    env_file:
      - path: config/mssql.env
    healthcheck:
      test: [
        "CMD",
        "/opt/mssql-tools/bin/sqlcmd",
        "-Usa",
        "-PMystr0ngP@ssw0rd!",
        "-Q",
        "select 1"]
      interval: 1s
      retries: 20
    ports:
      - "1433:1433"
    volumes:
      - mssqldb:/var/opt/mssql

  light-api:
    build:
      context: .
      dockerfile: EnergySector.LightSchedule.Host/Dockerfile
    env_file:
      - path: config/light_api.env
    ports:
     - "5050:5050"
     - "5051:5051"
    volumes:
      - ${APP_CERT_PATH}:/https/
    depends_on:
      mssql-db:
        condition: service_healthy

volumes:
  mssqldb:
